version: '3'

services:
  ms-auth-api:
    build:
      context: ./auth-api
      dockerfile: ./Dockerfile.dev
    container_name: ms-auth-api
    environment:
      NODE_ENV: container
      API_SECRET: YXV0aC1hcGktc2VjcmV0LWNvbnRhaW5lci0xMjM0NTY=
      PORT: 3000
      DB_HOST: ms-auth-db
      DB_PORT: 5432
      DB_USER: ms-auth-db
      DB_PASS: ms-auth-db
      DB_DATABASE: ms-auth-db
    ports:
      - 3000:3000
    volumes:
      - ./auth-api:/workspace:cached
    networks:
      - ms-network
    depends_on:
      - ms-auth-db
    command: sleep infinity

  ms-auth-db:
    image: postgres:latest
    container_name: ms-auth-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ms-auth-db
      POSTGRES_PASSWORD: ms-auth-db
      POSTGRES_DB: ms-auth-db
    ports:
      - 5432:5432
    volumes:
      - ms-auth-db:/var/lib/postgresql/data
    networks:
      - ms-network

  ms-product-api:
    build:
      context: ./product-api
      dockerfile: ./Dockerfile.dev
    container_name: ms-product-api
    environment:
      API_SECRET: YXV0aC1hcGktc2VjcmV0LWNvbnRhaW5lci0xMjM0NTY=
      PORT: 3333
      DB_HOST: ms-product-db
      DB_PORT: 5433
      DB_USER: ms-product-db
      DB_PASS: ms-product-db
      DB_DATABASE: ms-product-db
      RABBIT_MQ_HOST: ms-rabbitmq
      RABBIT_MQ_PORT: 5672
      RABBIT_MQ_USERNAME: ms-rabbitmq
      RABBIT_MQ_PASSWORD: ms-rabbitmq
      SALES_SERVICE_HOST: ms-sales-api
      SALES_SERVICE_PORT: 8080
    ports:
      - 3333:3333
    volumes:
      - ./product-api:/workspace:cached
    networks:
      - ms-network
    depends_on:
      - ms-product-db
    command: sleep infinity

  ms-product-db:
    image: postgres:latest
    container_name: ms-product-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ms-product-db
      POSTGRES_PASSWORD: ms-product-db
      POSTGRES_DB: ms-product-db
    ports:
      - 5433:5432
    volumes:
      - ms-product-db:/var/lib/postgresql/data
    networks:
      - ms-network

  ms-sales-api:
    build:
      context: ./sales-api
      dockerfile: ./Dockerfile.dev
    container_name: ms-sales-api
    environment:
      API_SECRET: YXV0aC1hcGktc2VjcmV0LWNvbnRhaW5lci0xMjM0NTY=
      NODE_ENV: container
      PORT: 8080
      DB_HOST: ms-sales-db
      DB_PORT: 27017
      DB_USER: ms-sales-db
      DB_PASS: ms-sales-db
      DB_DATABASE: ms-sales-db
      RABBIT_MQ_HOST: ms-rabbitmq
      RABBIT_MQ_PORT: 5672
      RABBIT_MQ_USERNAME: ms-rabbitmq
      RABBIT_MQ_PASSWORD: ms-rabbitmq
      SALES_PRODUCT_HOST: ms-product-api
      SALES_PRODUCT_PORT: 3333
    ports:
      - 8080:8080
    volumes:
      - ./sales-api:/workspace:cached
    networks:
      - ms-network
    depends_on:
      - ms-sales-db
    command: sleep infinity

  ms-sales-db:
    image: mongo:latest
    container_name: ms-sales-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: ms-sales-db
      MONGO_INITDB_ROOT_USERNAME: ms-sales-db
      MONGO_INITDB_ROOT_PASSWORD: ms-sales-db
    volumes:
      - ms-sales-db:/data/db
    networks:
      - ms-network

  # ms-sales-db-dashboard:
  #   image: mongo-express
  #   restart: unless-stopped
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: ms-sales-db
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: ms-sales-db
  #     ME_CONFIG_MONGODB_URL: mongodb://ms-sales-db:ms-sales-db@ms-sales-db:27017/
  #   ports:
  #     - 8081:8081
  #   depends_on:
  #     - ms-sales-db
  #   networks:
  #     - ms-network

  ms-rabbitmq:
    image: rabbitmq:management
    container_name: ms-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ms-rabbitmq
      RABBITMQ_DEFAULT_PASS: ms-rabbitmq
    ports:
      - 5672:5672
      - 25676:25676
      - 15672:15672
    networks:
      - ms-network

volumes:
  ms-auth-db:
  ms-product-db:
  ms-sales-db:

networks:
  ms-network:
    driver: bridge
