FROM gradle:jdk17

# Install packages
RUN apt-get update \
    && apt-get install -y \
    git \
    vim \
    curl \
    unzip \
    zip

# Set the working directory to /workspace
WORKDIR /workspace
