server:
    port: ${PORT}

spring:
    main:
        allow-circular-references: true
        allow-bean-definition-overriding: true

    application:
        name: product-api

    data-source:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://ms-product-db:5432/ms-product-db
        username: ms-product-db
        password: ms-product-db
        initialization-mode: always
        initialize: true
        continue-on-error: true
        plataform: postgresql
        max-active: 3

    jpa:
        hibernate:
            ddl-auto: create-drop
            format_sql: true
        show_sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

    rabbitmq:
        host: ${RABBIT_MQ_HOST}
        port: ${RABBIT_MQ_PORT}
        username: ${RABBIT_MQ_USERNAME}
        password: ${RABBIT_MQ_PASSWORD}

app-config:
    secrets:
        api-secret: ${API_SECRET}

    rabbit:
        exchange:
            product: ${RABBIT_MQ_PRODUCT_TOPIC}

        routingKey:
            product-stock: ${RABBIT_MQ_STOCK_UPDATE_ROUTING_KEY}
            sales-confirmation: ${RABBIT_MQ_SALE_CONFIRMATION_ROUTING_KEY}

        queue:
            product-stock: ${RABBIT_MQ_STOCK_UPDATE_QUEUE}
            sales-confirmation: ${RABBIT_MQ_SALE_CONFIRMATION_QUEUE}

    services:
        sales: ${SALES_SERVICE_HOST}:${SALES_SERVICE_PORT}
