FROM node:20.4.0

RUN apt-get update && apt-get install -y \
    sudo \
    git \
    curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

# ARG USERNAME=auth-api
# ARG USER_UID=1001
# ARG USER_GID=$USER_UID

# RUN groupadd --gid $USER_GID $USERNAME \
#     && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME

# RUN chown -R $USERNAME:$USERNAME /workspace

# USER $USERNAME
